// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.example.proto;

/**
 * Protobuf type {@code proto.Mess}
 */
public final class Mess extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Mess)
    MessOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Mess.newBuilder() to construct.
  private Mess(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Mess() {
    type_ = 0;
    str_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Mess();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.proto.MessProto.internal_static_proto_Mess_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.proto.MessProto.internal_static_proto_Mess_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.proto.Mess.class, org.example.proto.Mess.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.proto.MessType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.proto.MessType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public org.example.proto.MessType getType() {
    org.example.proto.MessType result = org.example.proto.MessType.forNumber(type_);
    return result == null ? org.example.proto.MessType.UNRECOGNIZED : result;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_ = 0;
  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int SERIAL_NUM_FIELD_NUMBER = 3;
  private int serialNum_ = 0;
  /**
   * <code>int32 serial_num = 3;</code>
   * @return The serialNum.
   */
  @java.lang.Override
  public int getSerialNum() {
    return serialNum_;
  }

  public static final int CHECK_NUM_FIELD_NUMBER = 4;
  private int checkNum_ = 0;
  /**
   * <code>int32 check_num = 4;</code>
   * @return The checkNum.
   */
  @java.lang.Override
  public int getCheckNum() {
    return checkNum_;
  }

  public static final int ORIGIN_ID_FIELD_NUMBER = 5;
  private int originId_ = 0;
  /**
   * <code>int32 origin_id = 5;</code>
   * @return The originId.
   */
  @java.lang.Override
  public int getOriginId() {
    return originId_;
  }

  public static final int INTEGER1_FIELD_NUMBER = 6;
  private int integer1_ = 0;
  /**
   * <code>int32 integer1 = 6;</code>
   * @return The integer1.
   */
  @java.lang.Override
  public int getInteger1() {
    return integer1_;
  }

  public static final int INTEGER2_FIELD_NUMBER = 7;
  private int integer2_ = 0;
  /**
   * <code>int32 integer2 = 7;</code>
   * @return The integer2.
   */
  @java.lang.Override
  public int getInteger2() {
    return integer2_;
  }

  public static final int INTEGER3_FIELD_NUMBER = 8;
  private int integer3_ = 0;
  /**
   * <code>int32 integer3 = 8;</code>
   * @return The integer3.
   */
  @java.lang.Override
  public int getInteger3() {
    return integer3_;
  }

  public static final int STR_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object str_ = "";
  /**
   * <code>string str = 9;</code>
   * @return The str.
   */
  @java.lang.Override
  public java.lang.String getStr() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      str_ = s;
      return s;
    }
  }
  /**
   * <code>string str = 9;</code>
   * @return The bytes for str.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStrBytes() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      str_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != org.example.proto.MessType.ask_refresh.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (id_ != 0) {
      output.writeInt32(2, id_);
    }
    if (serialNum_ != 0) {
      output.writeInt32(3, serialNum_);
    }
    if (checkNum_ != 0) {
      output.writeInt32(4, checkNum_);
    }
    if (originId_ != 0) {
      output.writeInt32(5, originId_);
    }
    if (integer1_ != 0) {
      output.writeInt32(6, integer1_);
    }
    if (integer2_ != 0) {
      output.writeInt32(7, integer2_);
    }
    if (integer3_ != 0) {
      output.writeInt32(8, integer3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(str_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, str_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != org.example.proto.MessType.ask_refresh.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, id_);
    }
    if (serialNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, serialNum_);
    }
    if (checkNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, checkNum_);
    }
    if (originId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, originId_);
    }
    if (integer1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, integer1_);
    }
    if (integer2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, integer2_);
    }
    if (integer3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, integer3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(str_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, str_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.proto.Mess)) {
      return super.equals(obj);
    }
    org.example.proto.Mess other = (org.example.proto.Mess) obj;

    if (type_ != other.type_) return false;
    if (getId()
        != other.getId()) return false;
    if (getSerialNum()
        != other.getSerialNum()) return false;
    if (getCheckNum()
        != other.getCheckNum()) return false;
    if (getOriginId()
        != other.getOriginId()) return false;
    if (getInteger1()
        != other.getInteger1()) return false;
    if (getInteger2()
        != other.getInteger2()) return false;
    if (getInteger3()
        != other.getInteger3()) return false;
    if (!getStr()
        .equals(other.getStr())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + SERIAL_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getSerialNum();
    hash = (37 * hash) + CHECK_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getCheckNum();
    hash = (37 * hash) + ORIGIN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOriginId();
    hash = (37 * hash) + INTEGER1_FIELD_NUMBER;
    hash = (53 * hash) + getInteger1();
    hash = (37 * hash) + INTEGER2_FIELD_NUMBER;
    hash = (53 * hash) + getInteger2();
    hash = (37 * hash) + INTEGER3_FIELD_NUMBER;
    hash = (53 * hash) + getInteger3();
    hash = (37 * hash) + STR_FIELD_NUMBER;
    hash = (53 * hash) + getStr().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.proto.Mess parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.Mess parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.Mess parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.Mess parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.Mess parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.Mess parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.Mess parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.Mess parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.Mess parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.proto.Mess parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.Mess parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.Mess parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.proto.Mess prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Mess}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Mess)
      org.example.proto.MessOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.MessProto.internal_static_proto_Mess_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.MessProto.internal_static_proto_Mess_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.Mess.class, org.example.proto.Mess.Builder.class);
    }

    // Construct using org.example.proto.Mess.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      id_ = 0;
      serialNum_ = 0;
      checkNum_ = 0;
      originId_ = 0;
      integer1_ = 0;
      integer2_ = 0;
      integer3_ = 0;
      str_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.proto.MessProto.internal_static_proto_Mess_descriptor;
    }

    @java.lang.Override
    public org.example.proto.Mess getDefaultInstanceForType() {
      return org.example.proto.Mess.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.proto.Mess build() {
      org.example.proto.Mess result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.proto.Mess buildPartial() {
      org.example.proto.Mess result = new org.example.proto.Mess(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.proto.Mess result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.serialNum_ = serialNum_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.checkNum_ = checkNum_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.originId_ = originId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.integer1_ = integer1_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.integer2_ = integer2_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.integer3_ = integer3_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.str_ = str_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.proto.Mess) {
        return mergeFrom((org.example.proto.Mess)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.proto.Mess other) {
      if (other == org.example.proto.Mess.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getSerialNum() != 0) {
        setSerialNum(other.getSerialNum());
      }
      if (other.getCheckNum() != 0) {
        setCheckNum(other.getCheckNum());
      }
      if (other.getOriginId() != 0) {
        setOriginId(other.getOriginId());
      }
      if (other.getInteger1() != 0) {
        setInteger1(other.getInteger1());
      }
      if (other.getInteger2() != 0) {
        setInteger2(other.getInteger2());
      }
      if (other.getInteger3() != 0) {
        setInteger3(other.getInteger3());
      }
      if (!other.getStr().isEmpty()) {
        str_ = other.str_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              serialNum_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              checkNum_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              originId_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              integer1_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              integer2_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              integer3_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              str_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.proto.MessType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.proto.MessType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.MessType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public org.example.proto.MessType getType() {
      org.example.proto.MessType result = org.example.proto.MessType.forNumber(type_);
      return result == null ? org.example.proto.MessType.UNRECOGNIZED : result;
    }
    /**
     * <code>.proto.MessType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(org.example.proto.MessType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proto.MessType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = 0;
      onChanged();
      return this;
    }

    private int serialNum_ ;
    /**
     * <code>int32 serial_num = 3;</code>
     * @return The serialNum.
     */
    @java.lang.Override
    public int getSerialNum() {
      return serialNum_;
    }
    /**
     * <code>int32 serial_num = 3;</code>
     * @param value The serialNum to set.
     * @return This builder for chaining.
     */
    public Builder setSerialNum(int value) {

      serialNum_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 serial_num = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerialNum() {
      bitField0_ = (bitField0_ & ~0x00000004);
      serialNum_ = 0;
      onChanged();
      return this;
    }

    private int checkNum_ ;
    /**
     * <code>int32 check_num = 4;</code>
     * @return The checkNum.
     */
    @java.lang.Override
    public int getCheckNum() {
      return checkNum_;
    }
    /**
     * <code>int32 check_num = 4;</code>
     * @param value The checkNum to set.
     * @return This builder for chaining.
     */
    public Builder setCheckNum(int value) {

      checkNum_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 check_num = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCheckNum() {
      bitField0_ = (bitField0_ & ~0x00000008);
      checkNum_ = 0;
      onChanged();
      return this;
    }

    private int originId_ ;
    /**
     * <code>int32 origin_id = 5;</code>
     * @return The originId.
     */
    @java.lang.Override
    public int getOriginId() {
      return originId_;
    }
    /**
     * <code>int32 origin_id = 5;</code>
     * @param value The originId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginId(int value) {

      originId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 origin_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      originId_ = 0;
      onChanged();
      return this;
    }

    private int integer1_ ;
    /**
     * <code>int32 integer1 = 6;</code>
     * @return The integer1.
     */
    @java.lang.Override
    public int getInteger1() {
      return integer1_;
    }
    /**
     * <code>int32 integer1 = 6;</code>
     * @param value The integer1 to set.
     * @return This builder for chaining.
     */
    public Builder setInteger1(int value) {

      integer1_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 integer1 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInteger1() {
      bitField0_ = (bitField0_ & ~0x00000020);
      integer1_ = 0;
      onChanged();
      return this;
    }

    private int integer2_ ;
    /**
     * <code>int32 integer2 = 7;</code>
     * @return The integer2.
     */
    @java.lang.Override
    public int getInteger2() {
      return integer2_;
    }
    /**
     * <code>int32 integer2 = 7;</code>
     * @param value The integer2 to set.
     * @return This builder for chaining.
     */
    public Builder setInteger2(int value) {

      integer2_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 integer2 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearInteger2() {
      bitField0_ = (bitField0_ & ~0x00000040);
      integer2_ = 0;
      onChanged();
      return this;
    }

    private int integer3_ ;
    /**
     * <code>int32 integer3 = 8;</code>
     * @return The integer3.
     */
    @java.lang.Override
    public int getInteger3() {
      return integer3_;
    }
    /**
     * <code>int32 integer3 = 8;</code>
     * @param value The integer3 to set.
     * @return This builder for chaining.
     */
    public Builder setInteger3(int value) {

      integer3_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 integer3 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearInteger3() {
      bitField0_ = (bitField0_ & ~0x00000080);
      integer3_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object str_ = "";
    /**
     * <code>string str = 9;</code>
     * @return The str.
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string str = 9;</code>
     * @return The bytes for str.
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string str = 9;</code>
     * @param value The str to set.
     * @return This builder for chaining.
     */
    public Builder setStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      str_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string str = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStr() {
      str_ = getDefaultInstance().getStr();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string str = 9;</code>
     * @param value The bytes for str to set.
     * @return This builder for chaining.
     */
    public Builder setStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      str_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.Mess)
  }

  // @@protoc_insertion_point(class_scope:proto.Mess)
  private static final org.example.proto.Mess DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.proto.Mess();
  }

  public static org.example.proto.Mess getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Mess>
      PARSER = new com.google.protobuf.AbstractParser<Mess>() {
    @java.lang.Override
    public Mess parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Mess> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Mess> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.proto.Mess getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

