// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.example.proto;

public interface MessArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MessArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  java.util.List<org.example.proto.Mess> 
      getMessesList();
  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  org.example.proto.Mess getMesses(int index);
  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  int getMessesCount();
  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  java.util.List<? extends org.example.proto.MessOrBuilder> 
      getMessesOrBuilderList();
  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  org.example.proto.MessOrBuilder getMessesOrBuilder(
      int index);
}
