// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.example.proto;

/**
 * Protobuf enum {@code proto.MessArrayType}
 */
public enum MessArrayType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>normal = 0;</code>
   */
  normal(0),
  /**
   * <code>refresh = 1;</code>
   */
  refresh(1),
  /**
   * <code>load = 2;</code>
   */
  load(2),
  /**
   * <code>save = 3;</code>
   */
  save(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>normal = 0;</code>
   */
  public static final int normal_VALUE = 0;
  /**
   * <code>refresh = 1;</code>
   */
  public static final int refresh_VALUE = 1;
  /**
   * <code>load = 2;</code>
   */
  public static final int load_VALUE = 2;
  /**
   * <code>save = 3;</code>
   */
  public static final int save_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessArrayType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessArrayType forNumber(int value) {
    switch (value) {
      case 0: return normal;
      case 1: return refresh;
      case 2: return load;
      case 3: return save;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessArrayType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessArrayType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessArrayType>() {
          public MessArrayType findValueByNumber(int number) {
            return MessArrayType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.example.proto.MessProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final MessArrayType[] VALUES = values();

  public static MessArrayType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessArrayType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.MessArrayType)
}

