// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.example.proto;

public interface MessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Mess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.MessType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.proto.MessType type = 1;</code>
   * @return The type.
   */
  org.example.proto.MessType getType();

  /**
   * <pre>
   *在包准备发送阶段,此值为接收方的id,发送器根据此字段准备好发送的目的地.
   * </pre>
   *
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   * 在即将发送时id改为本机id(发送id)接收方可根据此值知道是谁发送给自己的
   * </pre>
   *
   * <code>int32 serial_num = 3;</code>
   * @return The serialNum.
   */
  int getSerialNum();

  /**
   * <code>int32 check_num = 4;</code>
   * @return The checkNum.
   */
  int getCheckNum();

  /**
   * <code>int32 origin_id = 5;</code>
   * @return The originId.
   */
  int getOriginId();

  /**
   * <code>int32 integer1 = 6;</code>
   * @return The integer1.
   */
  int getInteger1();

  /**
   * <code>int32 integer2 = 7;</code>
   * @return The integer2.
   */
  int getInteger2();

  /**
   * <code>int32 integer3 = 8;</code>
   * @return The integer3.
   */
  int getInteger3();

  /**
   * <code>string str = 9;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 9;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
