// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.example.proto;

/**
 * Protobuf type {@code proto.MessArray}
 */
public final class MessArray extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.MessArray)
    MessArrayOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessArray.newBuilder() to construct.
  private MessArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessArray() {
    type_ = 0;
    messes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessArray();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.proto.MessProto.internal_static_proto_MessArray_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.proto.MessProto.internal_static_proto_MessArray_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.proto.MessArray.class, org.example.proto.MessArray.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.proto.MessArrayType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.proto.MessArrayType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public org.example.proto.MessArrayType getType() {
    org.example.proto.MessArrayType result = org.example.proto.MessArrayType.forNumber(type_);
    return result == null ? org.example.proto.MessArrayType.UNRECOGNIZED : result;
  }

  public static final int MESSES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<org.example.proto.Mess> messes_;
  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.proto.Mess> getMessesList() {
    return messes_;
  }
  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.proto.MessOrBuilder> 
      getMessesOrBuilderList() {
    return messes_;
  }
  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  @java.lang.Override
  public int getMessesCount() {
    return messes_.size();
  }
  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  @java.lang.Override
  public org.example.proto.Mess getMesses(int index) {
    return messes_.get(index);
  }
  /**
   * <code>repeated .proto.Mess messes = 2;</code>
   */
  @java.lang.Override
  public org.example.proto.MessOrBuilder getMessesOrBuilder(
      int index) {
    return messes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != org.example.proto.MessArrayType.normal.getNumber()) {
      output.writeEnum(1, type_);
    }
    for (int i = 0; i < messes_.size(); i++) {
      output.writeMessage(2, messes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != org.example.proto.MessArrayType.normal.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    for (int i = 0; i < messes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, messes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.proto.MessArray)) {
      return super.equals(obj);
    }
    org.example.proto.MessArray other = (org.example.proto.MessArray) obj;

    if (type_ != other.type_) return false;
    if (!getMessesList()
        .equals(other.getMessesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (getMessesCount() > 0) {
      hash = (37 * hash) + MESSES_FIELD_NUMBER;
      hash = (53 * hash) + getMessesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.proto.MessArray parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.MessArray parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.MessArray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.MessArray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.MessArray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.MessArray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.MessArray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.MessArray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.MessArray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.proto.MessArray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.MessArray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.MessArray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.proto.MessArray prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.MessArray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.MessArray)
      org.example.proto.MessArrayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.MessProto.internal_static_proto_MessArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.MessProto.internal_static_proto_MessArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.MessArray.class, org.example.proto.MessArray.Builder.class);
    }

    // Construct using org.example.proto.MessArray.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      if (messesBuilder_ == null) {
        messes_ = java.util.Collections.emptyList();
      } else {
        messes_ = null;
        messesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.proto.MessProto.internal_static_proto_MessArray_descriptor;
    }

    @java.lang.Override
    public org.example.proto.MessArray getDefaultInstanceForType() {
      return org.example.proto.MessArray.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.proto.MessArray build() {
      org.example.proto.MessArray result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.proto.MessArray buildPartial() {
      org.example.proto.MessArray result = new org.example.proto.MessArray(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.proto.MessArray result) {
      if (messesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          messes_ = java.util.Collections.unmodifiableList(messes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.messes_ = messes_;
      } else {
        result.messes_ = messesBuilder_.build();
      }
    }

    private void buildPartial0(org.example.proto.MessArray result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.proto.MessArray) {
        return mergeFrom((org.example.proto.MessArray)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.proto.MessArray other) {
      if (other == org.example.proto.MessArray.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (messesBuilder_ == null) {
        if (!other.messes_.isEmpty()) {
          if (messes_.isEmpty()) {
            messes_ = other.messes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMessesIsMutable();
            messes_.addAll(other.messes_);
          }
          onChanged();
        }
      } else {
        if (!other.messes_.isEmpty()) {
          if (messesBuilder_.isEmpty()) {
            messesBuilder_.dispose();
            messesBuilder_ = null;
            messes_ = other.messes_;
            bitField0_ = (bitField0_ & ~0x00000002);
            messesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMessesFieldBuilder() : null;
          } else {
            messesBuilder_.addAllMessages(other.messes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              org.example.proto.Mess m =
                  input.readMessage(
                      org.example.proto.Mess.parser(),
                      extensionRegistry);
              if (messesBuilder_ == null) {
                ensureMessesIsMutable();
                messes_.add(m);
              } else {
                messesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.proto.MessArrayType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.proto.MessArrayType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.MessArrayType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public org.example.proto.MessArrayType getType() {
      org.example.proto.MessArrayType result = org.example.proto.MessArrayType.forNumber(type_);
      return result == null ? org.example.proto.MessArrayType.UNRECOGNIZED : result;
    }
    /**
     * <code>.proto.MessArrayType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(org.example.proto.MessArrayType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proto.MessArrayType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.example.proto.Mess> messes_ =
      java.util.Collections.emptyList();
    private void ensureMessesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        messes_ = new java.util.ArrayList<org.example.proto.Mess>(messes_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.proto.Mess, org.example.proto.Mess.Builder, org.example.proto.MessOrBuilder> messesBuilder_;

    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public java.util.List<org.example.proto.Mess> getMessesList() {
      if (messesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messes_);
      } else {
        return messesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public int getMessesCount() {
      if (messesBuilder_ == null) {
        return messes_.size();
      } else {
        return messesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public org.example.proto.Mess getMesses(int index) {
      if (messesBuilder_ == null) {
        return messes_.get(index);
      } else {
        return messesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public Builder setMesses(
        int index, org.example.proto.Mess value) {
      if (messesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessesIsMutable();
        messes_.set(index, value);
        onChanged();
      } else {
        messesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public Builder setMesses(
        int index, org.example.proto.Mess.Builder builderForValue) {
      if (messesBuilder_ == null) {
        ensureMessesIsMutable();
        messes_.set(index, builderForValue.build());
        onChanged();
      } else {
        messesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public Builder addMesses(org.example.proto.Mess value) {
      if (messesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessesIsMutable();
        messes_.add(value);
        onChanged();
      } else {
        messesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public Builder addMesses(
        int index, org.example.proto.Mess value) {
      if (messesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessesIsMutable();
        messes_.add(index, value);
        onChanged();
      } else {
        messesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public Builder addMesses(
        org.example.proto.Mess.Builder builderForValue) {
      if (messesBuilder_ == null) {
        ensureMessesIsMutable();
        messes_.add(builderForValue.build());
        onChanged();
      } else {
        messesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public Builder addMesses(
        int index, org.example.proto.Mess.Builder builderForValue) {
      if (messesBuilder_ == null) {
        ensureMessesIsMutable();
        messes_.add(index, builderForValue.build());
        onChanged();
      } else {
        messesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public Builder addAllMesses(
        java.lang.Iterable<? extends org.example.proto.Mess> values) {
      if (messesBuilder_ == null) {
        ensureMessesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messes_);
        onChanged();
      } else {
        messesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public Builder clearMesses() {
      if (messesBuilder_ == null) {
        messes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        messesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public Builder removeMesses(int index) {
      if (messesBuilder_ == null) {
        ensureMessesIsMutable();
        messes_.remove(index);
        onChanged();
      } else {
        messesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public org.example.proto.Mess.Builder getMessesBuilder(
        int index) {
      return getMessesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public org.example.proto.MessOrBuilder getMessesOrBuilder(
        int index) {
      if (messesBuilder_ == null) {
        return messes_.get(index);  } else {
        return messesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public java.util.List<? extends org.example.proto.MessOrBuilder> 
         getMessesOrBuilderList() {
      if (messesBuilder_ != null) {
        return messesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messes_);
      }
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public org.example.proto.Mess.Builder addMessesBuilder() {
      return getMessesFieldBuilder().addBuilder(
          org.example.proto.Mess.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public org.example.proto.Mess.Builder addMessesBuilder(
        int index) {
      return getMessesFieldBuilder().addBuilder(
          index, org.example.proto.Mess.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Mess messes = 2;</code>
     */
    public java.util.List<org.example.proto.Mess.Builder> 
         getMessesBuilderList() {
      return getMessesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.proto.Mess, org.example.proto.Mess.Builder, org.example.proto.MessOrBuilder> 
        getMessesFieldBuilder() {
      if (messesBuilder_ == null) {
        messesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.proto.Mess, org.example.proto.Mess.Builder, org.example.proto.MessOrBuilder>(
                messes_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        messes_ = null;
      }
      return messesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.MessArray)
  }

  // @@protoc_insertion_point(class_scope:proto.MessArray)
  private static final org.example.proto.MessArray DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.proto.MessArray();
  }

  public static org.example.proto.MessArray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessArray>
      PARSER = new com.google.protobuf.AbstractParser<MessArray>() {
    @java.lang.Override
    public MessArray parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessArray> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessArray> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.proto.MessArray getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

